"""add_auth_fields_to_services

Revision ID: 574874d13107
Revises: c7a50d642d7d
Create Date: 2026-02-08 21:30:07.334083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574874d13107'
down_revision: Union[str, Sequence[str], None] = 'c7a50d642d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Added server_default for SQLite compatibility (cannot add NOT NULL without default)
    op.add_column('services', sa.Column('auth_type', sa.String(length=20), nullable=False, server_default='none', comment='认证类型：none/api_key/basic/oauth2'))
    op.add_column('services', sa.Column('auth_config', sa.JSON(), nullable=False, server_default='{}', comment='认证配置 JSON'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'auth_config')
    op.drop_column('services', 'auth_type')
    # ### end Alembic commands ###
